
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: event_booking_development
  port: 4556
  host : localhost
  username: postgres
  password: meshu

test:
  <<: *default
  database: event_booking_test
  port: 4556
  host : localhost
  username: postgres
  password: meshu



production:
  <<: *default
  database: event_booking_production
  username: event_booking
  password: <%= ENV["EVENT_BOOKING_DATABASE_PASSWORD"] %>
